### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by bsharper** [AkashKarnatak/ytgpt#2]
When I run `npm run bundle` after running `npm install` I get the following error:

Error: Can't walk dependency graph: Cannot find module '@microsoft/fetch-event-source' from '/home/user/projects/ytgpt/src/background.js'

Tried on node v18.16.1, and v21.6.1 and on macOS and Linux (Debian-based). Also tried with pnpm and got the same error.

**Comment by AkashKarnatak** [comment]
It seems like '@microsoft/fetch-event-source' didn't install properly. Can you confirm whether '@microsoft/fetch-event-source' exists inside node_modules folder

**Comment by AkashKarnatak** [comment]
I have updated my fork of `@microsoft/fetch-event-source` to include lib files in the git repo, as I directly install from github. This issue has now been fixed.
